# 3x3 Householder QR Demo

Copyright (C) 2020 Andreas Kloeckner

<details>
<summary>MIT License</summary>
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
</details>

This demo constructs a $3\times 3$ QR factorization using Householder reflectors.

In [2]:
import numpy as np
import numpy.linalg as la

In [3]:
n = 3

e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

A = np.random.randn(n, n)
A

array([[-1.24827164, -1.22141317,  0.95631552],
       [ 1.20623233,  1.32065379,  1.05558022],
       [-0.093254  , -1.99638212,  0.0128839 ]])

Householder reflector:
$$I-2\frac{vv^T}{v^Tv}$$

Choose $v=a-\|a\|e_1$.

In [4]:
#clear
a = A[:, 0]
v = a-la.norm(a)*e1

H1 = np.eye(3) - 2*np.outer(v, v)/(v@v)

In [5]:
A1 = H1 @ A
A1

array([[ 1.73835405e+00,  1.90055721e+00,  4.50609983e-02],
       [-4.00721123e-16,  5.97587254e-02,  1.42361585e+00],
       [ 1.38777878e-17, -1.89890214e+00, -1.55689853e-02]])

NB: Never build full Householder matrices in actual code! (Why? How?)

In [6]:
#clear
a = A1[:, 1].copy()
a[0] = 0
v = a-la.norm(a)*e2

H2 = np.eye(3) - 2*np.outer(v, v)/(v@v)

In [7]:
R = H2 @ A1
R

array([[ 1.73835405e+00,  1.90055721e+00,  4.50609983e-02],
       [-2.64754326e-17,  1.89984221e+00,  6.03405099e-02],
       [ 4.00086319e-16, -8.32667268e-17, -1.42242170e+00]])

In [8]:
Q = np.dot(H2, H1).T
la.norm(np.dot(Q, R) - A)

7.814885939201831e-16